/**
 * Isolation Runner for Telegram bot
 *
 * Executes commands using the `$` CLI from start-command with isolation backends
 * (screen, tmux, docker). Uses GUIDs for unique session tracking and
 * `$ --status <uuid>` for reliable completion detection.
 *
 * Uses command-stream library to invoke the globally-installed `$` CLI,
 * following the same pattern as claude.lib.mjs, agent.lib.mjs, etc.
 *
 * @see https://github.com/link-foundation/start
 * @see https://github.com/link-assistant/hive-mind/issues/380
 */

import crypto from 'crypto';

if (typeof use === 'undefined') {
  globalThis.use = (await eval(await (await fetch('https://unpkg.com/use-m/use.js')).text())).use;
}

const { $ } = await use('command-stream');

// Valid isolation backends
const VALID_ISOLATION_BACKENDS = ['screen', 'tmux', 'docker'];

/**
 * Generate a UUID v4 for unique session identification
 * @returns {string} UUID v4 string
 */
export function generateSessionId() {
  return crypto.randomUUID();
}

/**
 * Find the `$` CLI binary path
 * @returns {Promise<string|null>} Path to `$` binary or null
 */
async function findStartCommandBinary() {
  try {
    const result = await $`which $`;
    const path = result.stdout?.toString().trim() || '';
    return path || null;
  } catch {
    return null;
  }
}

/**
 * Execute a command with isolation via `$` from start-command
 *
 * @param {string} command - The command to run (e.g., 'solve')
 * @param {string[]} args - Arguments for the command
 * @param {Object} options - Isolation options
 * @param {string} options.backend - Isolation backend: 'screen', 'tmux', or 'docker'
 * @param {string} [options.sessionId] - UUID for session tracking (auto-generated if not provided)
 * @param {boolean} [options.verbose] - Enable verbose logging
 * @returns {Promise<{success: boolean, sessionId: string, output: string, error?: string, warning?: string}>}
 */
export async function executeWithIsolation(command, args, options = {}) {
  const { backend, verbose = false } = options;
  const sessionId = options.sessionId || generateSessionId();

  if (!VALID_ISOLATION_BACKENDS.includes(backend)) {
    return {
      success: false,
      sessionId,
      output: '',
      error: `Invalid isolation backend: '${backend}'. Must be one of: ${VALID_ISOLATION_BACKENDS.join(', ')}`,
    };
  }

  const binPath = await findStartCommandBinary();
  if (!binPath) {
    return {
      success: false,
      sessionId,
      output: '',
      warning: '⚠️ WARNING: start-command ($) not found in PATH\nPlease install: npm install -g start-command',
      error: 'start-command ($) not found',
    };
  }

  if (verbose) {
    console.log(`[VERBOSE] isolation-runner: Using $ binary at: ${binPath}`);
    console.log(`[VERBOSE] isolation-runner: Backend: ${backend}, Session ID: ${sessionId}`);
  }

  // Build arguments as array for the $ CLI:
  // $ --isolated <backend> --detached --session <sessionId> -- <command> <args...>
  const argsStr = args.join(' ');

  if (verbose) {
    console.log(`[VERBOSE] isolation-runner: $ --isolated ${backend} --detached --session ${sessionId} -- ${command} ${argsStr}`);
  }

  try {
    const result = await $({ mirror: false })`${binPath} --isolated ${backend} --detached --session ${sessionId} -- ${command} ${argsStr}`;

    const stdout = result.stdout?.toString() || '';
    const stderr = result.stderr?.toString() || '';
    const output = stdout + (stderr ? '\n' + stderr : '');

    if (verbose) {
      console.log(`[VERBOSE] isolation-runner: Output: ${output.substring(0, 500)}`);
    }

    // Extract the internal UUID generated by the $ CLI from its output.
    // The $ CLI creates its own UUID (different from our --session name) and
    // only $ --status works with that internal UUID, not our session name.
    // See: https://github.com/link-assistant/hive-mind/issues/1545
    const internalUuid = extractInternalUuid(output);
    if (verbose && internalUuid) {
      console.log(`[VERBOSE] isolation-runner: Extracted internal $ UUID: ${internalUuid} (screen session: ${sessionId})`);
    }

    return {
      success: true,
      sessionId,
      internalUuid,
      output: output.trim(),
    };
  } catch (error) {
    const stdout = error.stdout?.toString() || '';
    const stderr = error.stderr?.toString() || '';
    const output = stdout + stderr;

    if (verbose) {
      console.error(`[VERBOSE] isolation-runner: Error: ${error.message}`);
      console.error(`[VERBOSE] isolation-runner: Output: ${output.substring(0, 500)}`);
    }

    return {
      success: false,
      sessionId,
      internalUuid: null,
      output: output.trim(),
      error: error.message,
    };
  }
}

/**
 * Extract the internal UUID generated by the $ CLI from its output.
 * The $ CLI creates its own UUID separate from the --session name we provide.
 * Only $ --status works with the internal UUID, not the screen session name.
 *
 * @param {string} output - The stdout output from the $ CLI
 * @returns {string|null} The internal UUID or null if not found
 * @see https://github.com/link-assistant/hive-mind/issues/1545
 */
function extractInternalUuid(output) {
  // Match "session   <uuid>" or "│ session   <uuid>" from $ CLI output
  const match = output.match(/session\s+([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/i);
  return match ? match[1] : null;
}

/**
 * Query the status of an isolated session via `$ --status <uuid>`
 *
 * @param {string} sessionId - UUID of the session to check
 * @param {boolean} [verbose] - Enable verbose logging
 * @returns {Promise<{exists: boolean, status: string|null, exitCode: number|null, raw: string}>}
 */
export async function querySessionStatus(sessionId, verbose = false) {
  const binPath = await findStartCommandBinary();
  if (!binPath) {
    if (verbose) {
      console.log('[VERBOSE] isolation-runner: Cannot query status - $ binary not found');
    }
    return { exists: false, status: null, exitCode: null, raw: '' };
  }

  try {
    const result = await $({ mirror: false })`${binPath} --status ${sessionId} --output-format json`;

    const stdout = result.stdout?.toString().trim() || '';

    if (verbose) {
      console.log(`[VERBOSE] isolation-runner: Status query result: ${stdout.substring(0, 300)}`);
    }

    try {
      const data = JSON.parse(stdout);
      return {
        exists: true,
        status: data.status || null,
        exitCode: data.exitCode !== undefined ? data.exitCode : null,
        raw: stdout,
      };
    } catch {
      // If JSON parsing fails, try text-based detection
      const isExecuting = stdout.includes('executing');
      const isExecuted = stdout.includes('executed');
      return {
        exists: isExecuting || isExecuted,
        status: isExecuting ? 'executing' : isExecuted ? 'executed' : null,
        exitCode: null,
        raw: stdout,
      };
    }
  } catch (error) {
    if (verbose) {
      console.log(`[VERBOSE] isolation-runner: Status query error: ${error.message}`);
    }
    return { exists: false, status: null, exitCode: null, raw: '' };
  }
}

/**
 * Check if a screen session exists via `screen -ls`.
 * Used as a fallback when `$ --status` fails to find or correctly track
 * screen-based isolation sessions.
 *
 * @param {string} sessionName - Name of the screen session to check
 * @param {boolean} [verbose] - Enable verbose logging
 * @returns {Promise<boolean>} True if screen session exists
 * @see https://github.com/link-assistant/hive-mind/issues/1545
 */
export async function checkScreenSessionRunning(sessionName, verbose = false) {
  try {
    const result = await $({ mirror: false })`screen -ls`;
    const output = result.stdout?.toString() || '';
    const exists = output.includes(sessionName);
    if (verbose) {
      console.log(`[VERBOSE] isolation-runner: screen -ls check for '${sessionName}': ${exists ? 'running' : 'not found'}`);
    }
    return exists;
  } catch {
    // screen -ls returns exit code 1 when no sessions exist
    return false;
  }
}

/**
 * Check if an isolated session is still running.
 * Uses `$ --status` first, with a `screen -ls` fallback for screen-backend
 * sessions to work around start-command UUID mismatch issues.
 *
 * @param {string} sessionId - UUID of the session (used for both $ --status and screen session name)
 * @param {Object} [options] - Options
 * @param {string} [options.backend] - Isolation backend ('screen', 'tmux', 'docker')
 * @param {string} [options.internalUuid] - Internal UUID from $ CLI (if different from sessionId)
 * @param {boolean} [options.verbose] - Enable verbose logging
 * @returns {Promise<boolean>} True if session is still executing
 */
export async function isSessionRunning(sessionId, options = {}) {
  // Support legacy call signature: isSessionRunning(sessionId, verbose)
  const opts = typeof options === 'boolean' ? { verbose: options } : options;
  const { backend, internalUuid, verbose = false } = opts;

  // Try $ --status with internal UUID first (if available), then with sessionId
  const uuidToQuery = internalUuid || sessionId;
  const result = await querySessionStatus(uuidToQuery, verbose);
  if (result.exists && result.status === 'executing') {
    return true;
  }

  // Fallback: for screen backend, check screen -ls directly.
  // This works around start-command bugs where:
  // 1. $ --status can't find session by --session name (only by internal UUID)
  // 2. $ --status reports "executed" immediately for --detached screen sessions
  // See: https://github.com/link-assistant/hive-mind/issues/1545
  if (backend === 'screen') {
    const screenRunning = await checkScreenSessionRunning(sessionId, verbose);
    if (screenRunning && verbose) {
      console.log(`[VERBOSE] isolation-runner: $ --status says not running, but screen -ls confirms session '${sessionId}' is still active`);
    }
    return screenRunning;
  }

  return false;
}

/**
 * Validate that an isolation backend value is valid
 * @param {string} backend - Backend value to validate
 * @returns {boolean}
 */
export function isValidIsolationBackend(backend) {
  return VALID_ISOLATION_BACKENDS.includes(backend);
}

export { VALID_ISOLATION_BACKENDS };
