#!/usr/bin/env node

/**
 * Pure helpers for `/solve <github-repository-url>` — "repository mode"
 * (issue #2212).
 *
 * When `/solve` is given a repository URL instead of an issue or pull request
 * URL, it behaves similarly to `/fix --ci-cd`: it collects data about the
 * repository, creates a single combined issue that lists every open issue in
 * the repository as a GitHub native sub-issue, and then solves that combined
 * issue as it normally would — producing one pull request that closes all of
 * them at once.
 *
 * GitHub allows at most 100 sub-issues per parent issue
 * (https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/adding-sub-issues),
 * so when a repository has more open issues only the oldest 100 are attached
 * and the rest are intentionally left out of this run.
 *
 * Everything in this module is network- and filesystem-free so it can be unit
 * tested without GitHub access. The network side lives in
 * `solve.repository-mode.run.lib.mjs`.
 */

/**
 * GitHub's documented maximum number of sub-issues per parent issue.
 * @see https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/adding-sub-issues
 */
export const MAX_SUB_ISSUES_PER_PARENT = 100;

/** Marker that identifies an issue generated by `/solve <repository-url>`. */
export const REPOSITORY_MODE_MARKER = '<!-- hive-mind-solve-repository-mode -->';

/**
 * Build the `gh api` arguments that list every open issue of a repository,
 * oldest first.
 *
 * The REST `/issues` endpoint also returns pull requests; they are filtered out
 * by {@link isPullRequestEntry}. `--paginate` is required because the endpoint
 * returns at most 100 entries per page.
 *
 * @param {object} params
 * @param {string} params.owner
 * @param {string} params.repo
 * @param {number} [params.perPage=100]
 * @returns {string[]} argument list for `gh`
 */
export function buildOpenIssuesApiArgs({ owner, repo, perPage = MAX_SUB_ISSUES_PER_PARENT }) {
  if (!owner || !repo) throw new Error('buildOpenIssuesApiArgs requires owner and repo');
  const size = Number(perPage);
  const safePerPage = Number.isInteger(size) && size >= 1 && size <= 100 ? size : MAX_SUB_ISSUES_PER_PARENT;
  // Query parameters must be part of the endpoint string: `gh api -f key=value`
  // switches the request to POST, which makes this endpoint fail with
  // HTTP 422 ("title wasn't supplied").
  return ['api', `repos/${owner}/${repo}/issues?state=open&sort=created&direction=asc&per_page=${safePerPage}`, '--paginate'];
}

/**
 * The REST issues endpoint returns pull requests alongside issues; a pull
 * request is identified by the presence of a `pull_request` object.
 *
 * @param {object} entry - raw REST issue entry
 * @returns {boolean}
 */
export function isPullRequestEntry(entry) {
  return Boolean(entry && typeof entry === 'object' && entry.pull_request);
}

/**
 * Normalize a raw REST issue entry into the minimal shape the rest of
 * repository mode needs.
 *
 * `id` is the REST database id (not the GraphQL node id): the sub-issues API
 * takes `sub_issue_id` as a REST id.
 *
 * @param {object} entry
 * @returns {{number: number, id: number, title: string, url: string, createdAt: string}|null}
 */
export function normalizeOpenIssueEntry(entry) {
  if (!entry || typeof entry !== 'object') return null;
  const number = Number(entry.number);
  const id = Number(entry.id);
  if (!Number.isInteger(number) || number <= 0) return null;
  return {
    number,
    id: Number.isInteger(id) && id > 0 ? id : null,
    title: String(entry.title || '').trim(),
    url: String(entry.html_url || '').trim(),
    createdAt: String(entry.created_at || '').trim(),
  };
}

/**
 * Filter out pull requests, normalize, sort oldest-first and cap the list at
 * `limit` entries.
 *
 * Sorting is done here (not only server-side) so the selection is deterministic
 * even when the caller passes an unsorted list. Ties fall back to the issue
 * number, which is monotonic per repository.
 *
 * @param {Array<object>} entries - raw REST issue entries
 * @param {object} [options]
 * @param {number} [options.limit=MAX_SUB_ISSUES_PER_PARENT]
 * @param {Array<number>} [options.exclude] - issue numbers to skip
 * @returns {{selected: Array<object>, totalOpen: number, skipped: number}}
 */
export function selectOldestOpenIssues(entries, { limit = MAX_SUB_ISSUES_PER_PARENT, exclude = [] } = {}) {
  const excluded = new Set((exclude || []).map(Number).filter(Number.isInteger));
  const issues = (Array.isArray(entries) ? entries : [])
    .filter(entry => !isPullRequestEntry(entry))
    .map(normalizeOpenIssueEntry)
    .filter(Boolean)
    .filter(issue => !excluded.has(issue.number));

  issues.sort((a, b) => {
    const aTime = Date.parse(a.createdAt);
    const bTime = Date.parse(b.createdAt);
    if (Number.isFinite(aTime) && Number.isFinite(bTime) && aTime !== bTime) return aTime - bTime;
    return a.number - b.number;
  });

  const cap = Number.isFinite(limit) && limit > 0 ? Math.floor(limit) : MAX_SUB_ISSUES_PER_PARENT;
  const selected = issues.slice(0, cap);

  return {
    selected,
    totalOpen: issues.length,
    skipped: Math.max(0, issues.length - selected.length),
  };
}

/**
 * Title for the combined issue.
 *
 * @param {object} params
 * @param {string} params.owner
 * @param {string} params.repo
 * @param {number} params.count - number of attached sub-issues
 * @param {number} params.totalOpen - total open issues found in the repository
 * @returns {string}
 */
export function buildCombinedIssueTitle({ owner, repo, count, totalOpen }) {
  const repository = `${owner}/${repo}`;
  if (totalOpen > count) {
    return `Address the ${count} oldest open issues in ${repository} (of ${totalOpen} open)`;
  }
  if (count === 1) {
    return `Address the single open issue in ${repository}`;
  }
  return `Address all ${count} open issues in ${repository}`;
}

function formatIssueLine(issue) {
  const created = issue.createdAt ? ` — opened ${issue.createdAt.slice(0, 10)}` : '';
  const title = issue.title ? ` ${issue.title}` : '';
  return `- [ ] #${issue.number}${title}${created}`;
}

/**
 * Build the closing-keyword block the pull request description must contain.
 *
 * GitHub requires the full syntax for *each* issue: a single keyword does not
 * apply to a comma separated list of issues
 * (https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue).
 *
 * @param {Array<{number: number}>} issues
 * @param {string} [keyword='Fixes']
 * @returns {string}
 */
export function buildClosingKeywordBlock(issues, keyword = 'Fixes') {
  return (Array.isArray(issues) ? issues : []).map(issue => `${keyword} #${issue.number}`).join('\n');
}

/**
 * Body of the combined issue.
 *
 * @param {object} params
 * @param {{owner: string, repo: string, url: string}} params.repository
 * @param {Array<object>} params.issues - selected sub-issues (oldest first)
 * @param {number} params.totalOpen
 * @param {number} [params.limit=MAX_SUB_ISSUES_PER_PARENT]
 * @param {string} [params.sourceIssueUrl] - issue that introduced repository mode
 * @returns {string}
 */
export function buildCombinedIssueBody({ repository, issues, totalOpen, limit = MAX_SUB_ISSUES_PER_PARENT, sourceIssueUrl = 'https://github.com/link-assistant/hive-mind/issues/2212' }) {
  const list = Array.isArray(issues) ? issues : [];
  const repositoryUrl = repository.url || `https://github.com/${repository.owner}/${repository.repo}`;
  const skipped = Math.max(0, Number(totalOpen || 0) - list.length);

  const lines = [REPOSITORY_MODE_MARKER, '', '## Objective', '', `Address every open issue listed below in [${repository.owner}/${repository.repo}](${repositoryUrl}) with a **single pull request**.`, '', `This issue was generated automatically by \`/solve ${repositoryUrl}\` (repository mode, see ${sourceIssueUrl}). Every issue below is attached to this issue as a GitHub native sub-issue.`, '', '## Scope', '', `- Open issues found in the repository: ${totalOpen}`, `- Issues attached as sub-issues of this issue: ${list.length}`, `- GitHub sub-issue limit per parent issue: ${limit}`];

  if (skipped > 0) {
    lines.push(`- Open issues intentionally left out of this run (newest ${skipped}, over the sub-issue limit): ${skipped}`);
  }

  lines.push('', '## Issues to address', '');

  if (list.length === 0) {
    lines.push('_No open issues were found._');
  } else {
    lines.push(...list.map(formatIssueLine));
  }

  lines.push('', '## Requirements', '', '1. Read every issue listed above (including its comments) and fully implement what it asks for.', '2. Do all of the work in this single pull request. Do not defer any listed issue to a follow-up pull request.', '3. The pull request description **must** close this issue and **every** issue listed above, so that merging the pull request closes all of them at once.', '4. GitHub requires the full closing syntax for each issue: one keyword per issue. `Fixes #1, #2` only closes `#1`. Use the block below verbatim (plus `Fixes #<this issue>` for this issue).', '5. If an issue turns out to be already resolved or not reproducible, say so explicitly in the pull request description — but still keep its closing reference so it is closed on merge.', '', '## Required closing references in the pull request description', '', '```', buildClosingKeywordBlock(list) || '(no issues)', '```', '');

  return lines.join('\n');
}

/**
 * Human-readable summary of what repository mode is about to do, for logs.
 *
 * @param {object} params
 * @returns {string[]}
 */
export function buildRepositoryModeSummaryLines({ totalOpen, selectedCount, skipped, limit = MAX_SUB_ISSUES_PER_PARENT }) {
  const lines = [`   Open issues found:        ${totalOpen}`, `   Attached as sub-issues:   ${selectedCount} (limit ${limit})`];
  if (skipped > 0) {
    lines.push(`   Left out (newest, over limit): ${skipped}`);
  }
  return lines;
}

export default {
  MAX_SUB_ISSUES_PER_PARENT,
  REPOSITORY_MODE_MARKER,
  buildOpenIssuesApiArgs,
  isPullRequestEntry,
  normalizeOpenIssueEntry,
  selectOldestOpenIssues,
  buildCombinedIssueTitle,
  buildClosingKeywordBlock,
  buildCombinedIssueBody,
  buildRepositoryModeSummaryLines,
};
